"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { ToolId } from "@/lib/tools/registry";

function load(importer: () => Promise<ComponentType>): ComponentType {
  return dynamic(async () => ({ default: await importer() }));
}

const TOOL_COMPONENTS: Record<ToolId, ComponentType> = {
  "pdf-merge": load(() => import("./pdf-tools").then((m) => m.PdfMerge)),
  "pdf-split": load(() => import("./pdf-tools").then((m) => m.PdfSplit)),
  "pdf-organize": load(() => import("./pdf-tools").then((m) => m.PdfOrganize)),
  "pdf-compress": load(() => import("./pdf-tools").then((m) => m.PdfCompress)),
  "pdf-watermark": load(() => import("./pdf-tools").then((m) => m.PdfWatermark)),
  "pdf-redact": load(() => import("./pdf-tools").then((m) => m.PdfRedact)),
  "pdf-extract": load(() => import("./pdf-tools").then((m) => m.PdfExtract)),
  "pdf-numbers": load(() => import("./pdf-extra-tools").then((m) => m.PdfNumbers)),
  "pdf-to-images": load(() => import("./pdf-extra-tools").then((m) => m.PdfToImages)),
  "images-to-pdf": load(() => import("./pdf-extra-tools").then((m) => m.ImagesToPdf)),
  "pdf-flatten": load(() => import("./pdf-extra-tools").then((m) => m.PdfFlatten)),
  "pdf-metadata": load(() => import("./pdf-extra-tools").then((m) => m.PdfMetadata)),
  "pdf-protect": load(() => import("./pdf-extra-tools").then((m) => m.PdfProtect)),
  "pdf-sign": load(() => import("./pdf-extra-tools").then((m) => m.PdfSign)),
  "image-compress": load(() => import("./image-tools").then((m) => m.ImageCompress)),
  "image-resize": load(() => import("./image-tools").then((m) => m.ImageResize)),
  "image-crop": load(() => import("./image-tools").then((m) => m.ImageCrop)),
  "image-convert": load(() => import("./image-tools").then((m) => m.ImageConvert)),
  "image-metadata": load(() => import("./image-tools").then((m) => m.ImageMetadata)),
  "image-adjust": load(() => import("./image-tools").then((m) => m.ImageAdjust)),
  "image-rotate": load(() => import("./image-extra-tools").then((m) => m.ImageRotate)),
  "image-filters": load(() => import("./image-extra-tools").then((m) => m.ImageFilters)),
  "image-favicon": load(() => import("./image-extra-tools").then((m) => m.ImageFavicon)),
  "image-watermark": load(() => import("./image-extra-tools").then((m) => m.ImageWatermark)),
  "image-palette": load(() => import("./kit-new-tools").then((m) => m.ImagePalette)),
  "audio-convert": load(() => import("./audio-tools").then((m) => m.AudioConvert)),
  "audio-trim": load(() => import("./audio-tools").then((m) => m.AudioTrim)),
  "audio-speed": load(() => import("./audio-tools").then((m) => m.AudioSpeed)),
  "video-convert": load(() => import("./video-tools").then((m) => m.VideoConvert)),
  "video-trim": load(() => import("./video-tools").then((m) => m.VideoTrim)),
  "video-speed": load(() => import("./video-tools").then((m) => m.VideoSpeed)),
  "video-extract-audio": load(() => import("./video-tools").then((m) => m.VideoExtractAudio)),
  "video-gif": load(() => import("./video-tools").then((m) => m.VideoGif)),
  "convert-hub": load(() => import("./convert-tools").then((m) => m.ConvertHub)),
  "json-format": load(() => import("./text-tools").then((m) => m.JsonFormat)),
  "yaml-format": load(() => import("./text-tools").then((m) => m.YamlFormat)),
  "toml-format": load(() => import("./text-tools").then((m) => m.TomlFormat)),
  "markdown-html": load(() => import("./text-tools").then((m) => m.MarkdownHtml)),
  "csv-json": load(() => import("./text-tools").then((m) => m.CsvJson)),
  "text-diff": load(() => import("./text-tools").then((m) => m.TextDiff)),
  "base64": load(() => import("./text-tools").then((m) => m.Base64Tool)),
  "url-encode": load(() => import("./text-tools").then((m) => m.UrlEncodeTool)),
  "xml-json": load(() => import("./text-extra-tools").then((m) => m.XmlJson)),
  "sql-format": load(() => import("./text-extra-tools").then((m) => m.SqlFormat)),
  "regex-tester": load(() => import("./text-extra-tools").then((m) => m.RegexTester)),
  "hash-generator": load(() => import("./text-extra-tools").then((m) => m.HashGenerator)),
  "uuid-generator": load(() => import("./text-extra-tools").then((m) => m.UuidGenerator)),
  "color-convert": load(() => import("./text-extra-tools").then((m) => m.ColorConvert)),
  "lorem-ipsum": load(() => import("./text-extra-tools").then((m) => m.LoremIpsum)),
  "qr-code": load(() => import("./text-extra-tools").then((m) => m.QrCodeTool)),
  "password-generator": load(() => import("./work-tools").then((m) => m.PasswordGenerator)),
  "case-convert": load(() => import("./work-tools").then((m) => m.CaseConvert)),
  "jwt-decode": load(() => import("./work-tools").then((m) => m.JwtDecode)),
  "unix-timestamp": load(() => import("./work-tools").then((m) => m.UnixTimestamp)),
  "cron-explain": load(() => import("./work-tools").then((m) => m.CronExplain)),
  "number-base": load(() => import("./work-tools").then((m) => m.NumberBase)),
  "html-entities": load(() => import("./work-tools").then((m) => m.HtmlEntities)),
  "json-types": load(() => import("./work-tools").then((m) => m.JsonTypes)),
  "json-query": load(() => import("./kit-new-tools").then((m) => m.JsonQuery)),
  "text-lines": load(() => import("./kit-new-tools").then((m) => m.TextLines)),
  "slugify": load(() => import("./kit-new-tools").then((m) => m.SlugifyTool)),
  "color-contrast": load(() => import("./kit-new-tools").then((m) => m.ColorContrast)),
  "check-digits": load(() => import("./kit-new-tools").then((m) => m.CheckDigits)),
  "aspect-ratio": load(() => import("./kit-new-tools").then((m) => m.AspectRatioTool)),
  "percentage-calculator": load(() => import("./kit-new-tools").then((m) => m.PercentageCalculator)),
  "loan-calculator": load(() => import("./kit-new-tools").then((m) => m.LoanCalculator)),
  "meeting-planner": load(() => import("./kit-new-tools").then((m) => m.MeetingPlanner)),
  "currency-converter": load(() => import("./converter-tools").then((m) => m.CurrencyConverterTool)),
  "length-converter": load(() => import("./converter-tools").then((m) => m.LengthConverter)),
  "mass-converter": load(() => import("./converter-tools").then((m) => m.MassConverter)),
  "temperature-converter": load(() => import("./converter-tools").then((m) => m.TemperatureConverter)),
  "speed-converter": load(() => import("./converter-tools").then((m) => m.SpeedConverter)),
  "duration-converter": load(() => import("./converter-tools").then((m) => m.DurationConverter)),
  "volume-converter": load(() => import("./converter-tools").then((m) => m.VolumeConverter)),
  "power-converter": load(() => import("./converter-tools").then((m) => m.PowerConverter)),
  "energy-converter": load(() => import("./converter-tools").then((m) => m.EnergyConverter)),
  "pressure-converter": load(() => import("./converter-tools").then((m) => m.PressureConverter)),
  "area-converter": load(() => import("./converter-tools").then((m) => m.AreaConverter)),
  "data-converter": load(() => import("./converter-tools").then((m) => m.DataConverter)),
  "angle-converter": load(() => import("./converter-tools").then((m) => m.AngleConverter)),
  "frequency-converter": load(() => import("./converter-tools").then((m) => m.FrequencyConverter)),
  "force-converter": load(() => import("./converter-tools").then((m) => m.ForceConverter)),
  "fuel-economy-converter": load(() => import("./converter-tools").then((m) => m.FuelEconomyConverter)),
  "acceleration-converter": load(() => import("./converter-tools").then((m) => m.AccelerationConverter)),
  "torque-converter": load(() => import("./converter-tools").then((m) => m.TorqueConverter)),
  "electrical-converter": load(() => import("./converter-tools").then((m) => m.ElectricalConverter)),
  "typography-converter": load(() => import("./converter-tools").then((m) => m.TypographyConverter)),
  "text-counter": load(() => import("./everyday-tools").then((m) => m.TextCounter)),
  "timezone-converter": load(() => import("./everyday-tools").then((m) => m.TimezoneConverter)),
  "date-calculator": load(() => import("./everyday-tools").then((m) => m.DateCalculator)),
  "tip-split-calculator": load(() => import("./everyday-tools").then((m) => m.TipSplitCalculator)),
  "bmi-calorie-calculator": load(() => import("./bmi-calorie-tools").then((m) => m.BmiCalorieCalculator)),
  "stopwatch-timer": load(() => import("./everyday-tools").then((m) => m.StopwatchTimer)),
  "random-generator": load(() => import("./everyday-tools").then((m) => m.RandomGenerator)),
};

export function ToolView({ toolId }: { toolId: ToolId }) {
  const Component = TOOL_COMPONENTS[toolId];
  if (!Component) return null;
  return <Component />;
}
