"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { ToolId } from "@/lib/tools/registry";

function load(importer: () => Promise<ComponentType>): ComponentType {
  return dynamic(async () => ({ default: await importer() }));
}

const TOOL_COMPONENTS: Record<ToolId, ComponentType> = {
  "pdf-merge": load(() => import("./pdf-merge").then((m) => m.PdfMerge)),
  "pdf-split": load(() => import("./pdf-split").then((m) => m.PdfSplit)),
  "pdf-organize": load(() => import("./pdf-organize").then((m) => m.PdfOrganize)),
  "pdf-compress": load(() => import("./pdf-compress").then((m) => m.PdfCompress)),
  "pdf-watermark": load(() => import("./pdf-watermark").then((m) => m.PdfWatermark)),
  "pdf-redact": load(() => import("./pdf-redact").then((m) => m.PdfRedact)),
  "pdf-extract": load(() => import("./pdf-extract").then((m) => m.PdfExtract)),
  "pdf-numbers": load(() => import("./pdf-numbers").then((m) => m.PdfNumbers)),
  "pdf-to-images": load(() => import("./pdf-to-images").then((m) => m.PdfToImages)),
  "images-to-pdf": load(() => import("./images-to-pdf").then((m) => m.ImagesToPdf)),
  "pdf-flatten": load(() => import("./pdf-flatten").then((m) => m.PdfFlatten)),
  "pdf-metadata": load(() => import("./pdf-metadata").then((m) => m.PdfMetadata)),
  "pdf-protect": load(() => import("./pdf-protect").then((m) => m.PdfProtect)),
  "pdf-sign": load(() => import("./pdf-sign").then((m) => m.PdfSign)),
  "image-compress": load(() => import("./image-compress").then((m) => m.ImageCompress)),
  "image-resize": load(() => import("./image-resize").then((m) => m.ImageResize)),
  "image-crop": load(() => import("./image-crop").then((m) => m.ImageCrop)),
  "image-convert": load(() => import("./image-convert").then((m) => m.ImageConvert)),
  "image-metadata": load(() => import("./image-metadata").then((m) => m.ImageMetadata)),
  "image-adjust": load(() => import("./image-adjust").then((m) => m.ImageAdjust)),
  "image-rotate": load(() => import("./image-rotate").then((m) => m.ImageRotate)),
  "image-filters": load(() => import("./image-filters").then((m) => m.ImageFilters)),
  "image-favicon": load(() => import("./image-favicon").then((m) => m.ImageFavicon)),
  "image-watermark": load(() => import("./image-watermark").then((m) => m.ImageWatermark)),
  "image-palette": load(() => import("./image-palette").then((m) => m.ImagePalette)),
  "audio-convert": load(() => import("./audio-convert").then((m) => m.AudioConvert)),
  "audio-trim": load(() => import("./audio-trim").then((m) => m.AudioTrim)),
  "audio-speed": load(() => import("./audio-speed").then((m) => m.AudioSpeed)),
  "video-convert": load(() => import("./video-convert").then((m) => m.VideoConvert)),
  "video-trim": load(() => import("./video-trim").then((m) => m.VideoTrim)),
  "video-speed": load(() => import("./video-speed").then((m) => m.VideoSpeed)),
  "video-extract-audio": load(() => import("./video-extract-audio").then((m) => m.VideoExtractAudio)),
  "video-gif": load(() => import("./video-gif").then((m) => m.VideoGif)),
  "convert-hub": load(() => import("./convert-tools").then((m) => m.ConvertHub)),
  "json-format": load(() => import("./json-format").then((m) => m.JsonFormat)),
  "yaml-format": load(() => import("./yaml-format").then((m) => m.YamlFormat)),
  "toml-format": load(() => import("./toml-format").then((m) => m.TomlFormat)),
  "markdown-html": load(() => import("./markdown-html").then((m) => m.MarkdownHtml)),
  "csv-json": load(() => import("./csv-json").then((m) => m.CsvJson)),
  "text-diff": load(() => import("./text-diff").then((m) => m.TextDiff)),
  "base64": load(() => import("./base64").then((m) => m.Base64Tool)),
  "url-encode": load(() => import("./url-encode").then((m) => m.UrlEncodeTool)),
  "xml-json": load(() => import("./xml-json").then((m) => m.XmlJson)),
  "sql-format": load(() => import("./sql-format").then((m) => m.SqlFormat)),
  "regex-tester": load(() => import("./regex-tester").then((m) => m.RegexTester)),
  "hash-generator": load(() => import("./hash-generator").then((m) => m.HashGenerator)),
  "uuid-generator": load(() => import("./uuid-generator").then((m) => m.UuidGenerator)),
  "color-convert": load(() => import("./color-convert").then((m) => m.ColorConvert)),
  "lorem-ipsum": load(() => import("./lorem-ipsum").then((m) => m.LoremIpsum)),
  "qr-code": load(() => import("./qr-code").then((m) => m.QrCodeTool)),
  "password-generator": load(() => import("./password-generator").then((m) => m.PasswordGenerator)),
  "case-convert": load(() => import("./case-convert").then((m) => m.CaseConvert)),
  "jwt-decode": load(() => import("./jwt-decode").then((m) => m.JwtDecode)),
  "unix-timestamp": load(() => import("./unix-timestamp").then((m) => m.UnixTimestamp)),
  "cron-explain": load(() => import("./cron-explain").then((m) => m.CronExplain)),
  "number-base": load(() => import("./number-base").then((m) => m.NumberBase)),
  "html-entities": load(() => import("./html-entities").then((m) => m.HtmlEntities)),
  "json-types": load(() => import("./json-types").then((m) => m.JsonTypes)),
  "json-query": load(() => import("./json-query").then((m) => m.JsonQuery)),
  "text-lines": load(() => import("./text-lines").then((m) => m.TextLines)),
  "slugify": load(() => import("./slugify").then((m) => m.SlugifyTool)),
  "color-contrast": load(() => import("./color-contrast").then((m) => m.ColorContrast)),
  "check-digits": load(() => import("./check-digits").then((m) => m.CheckDigits)),
  "aspect-ratio": load(() => import("./aspect-ratio").then((m) => m.AspectRatioTool)),
  "percentage-calculator": load(() => import("./percentage-calculator").then((m) => m.PercentageCalculator)),
  "loan-calculator": load(() => import("./loan-calculator").then((m) => m.LoanCalculator)),
  "meeting-planner": load(() => import("./meeting-planner").then((m) => m.MeetingPlanner)),
  "currency-converter": load(() => import("./currency-converter").then((m) => m.CurrencyConverterTool)),
  "length-converter": load(() => import("./unit-converter").then((m) => m.LengthConverter)),
  "mass-converter": load(() => import("./unit-converter").then((m) => m.MassConverter)),
  "temperature-converter": load(() => import("./unit-converter").then((m) => m.TemperatureConverter)),
  "speed-converter": load(() => import("./unit-converter").then((m) => m.SpeedConverter)),
  "duration-converter": load(() => import("./unit-converter").then((m) => m.DurationConverter)),
  "volume-converter": load(() => import("./unit-converter").then((m) => m.VolumeConverter)),
  "power-converter": load(() => import("./unit-converter").then((m) => m.PowerConverter)),
  "energy-converter": load(() => import("./unit-converter").then((m) => m.EnergyConverter)),
  "pressure-converter": load(() => import("./unit-converter").then((m) => m.PressureConverter)),
  "area-converter": load(() => import("./unit-converter").then((m) => m.AreaConverter)),
  "data-converter": load(() => import("./unit-converter").then((m) => m.DataConverter)),
  "angle-converter": load(() => import("./unit-converter").then((m) => m.AngleConverter)),
  "frequency-converter": load(() => import("./unit-converter").then((m) => m.FrequencyConverter)),
  "force-converter": load(() => import("./unit-converter").then((m) => m.ForceConverter)),
  "fuel-economy-converter": load(() => import("./unit-converter").then((m) => m.FuelEconomyConverter)),
  "acceleration-converter": load(() => import("./unit-converter").then((m) => m.AccelerationConverter)),
  "torque-converter": load(() => import("./unit-converter").then((m) => m.TorqueConverter)),
  "electrical-converter": load(() => import("./unit-converter").then((m) => m.ElectricalConverter)),
  "typography-converter": load(() => import("./unit-converter").then((m) => m.TypographyConverter)),
  "text-counter": load(() => import("./text-counter").then((m) => m.TextCounter)),
  "timezone-converter": load(() => import("./timezone-converter").then((m) => m.TimezoneConverter)),
  "date-calculator": load(() => import("./date-calculator").then((m) => m.DateCalculator)),
  "tip-split-calculator": load(() => import("./tip-split-calculator").then((m) => m.TipSplitCalculator)),
  "bmi-calorie-calculator": load(() => import("./bmi-calorie-tools").then((m) => m.BmiCalorieCalculator)),
  "stopwatch-timer": load(() => import("./stopwatch-timer").then((m) => m.StopwatchTimer)),
  "random-generator": load(() => import("./random-generator").then((m) => m.RandomGenerator)),
};

export function ToolView({ toolId }: { toolId: ToolId }) {
  const Component = TOOL_COMPONENTS[toolId];
  if (!Component) return null;
  return <Component />;
}
